### ISSUE TITLE
找不到image

### ISSUE THREAD

**Issue by caoler** [BlueSky-07/wechat-token#3]
-> first run detected, preparing runtime
-> building docker image
[+] Building 12.4s (3/3) FINISHED                                               
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 37B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/library/archlinux:lates  12.3s
------
 > [internal] load metadata for docker.io/library/archlinux:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:c35d8f0d3b17b5423ee1cd9c7661375449b58b45609ee6370a320b710fb8cea4: not found
-> runtime prepared

Unable to find image 'wechat-token:latest' locally
docker: Error response from daemon: pull access denied for wechat-token, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by BlueSky-07** [comment]
看起来是架构不支持，你用的是 Apple M1 吗？

**Comment by caoler** [comment]
@BlueSky-07  是的 M1

**Comment by BlueSky-07** [comment]
这个目前只能用 archlinux 的 image 才能运行，如果没有其他电脑的话，可以去 https://github.com/BlueSky-07/wechat-token/actions 里找一个最新的记录查看一下

**Comment by caoler** [comment]
@BlueSky-07  已经登录成功了 thx
