### ISSUE TITLE
非常感谢作者开发的组件！

### ISSUE THREAD

**Issue by dabao0903** [BlueSky-07/wechat-token#5]
非常感谢作者开发的组件，期待能和SmartIM4IntelliJ作者一起，集成到IntelliJ编辑器里面😀

https://github.com/Jamling/SmartIM4IntelliJ

**Comment by BlueSky-07** [comment]
没有写过 IntelliJ 的插件。
不过粗略看了下这个插件的实现，它用到了另一个封装好的微信请求库，要让这个插件能够使用当前的方法登陆应该是要找那个微信请求库的作者做升级，这样这个插件的作者才有可能更新调用来使用。

**Comment by dabao0903** [comment]
> 没有写过 IntelliJ 的插件。 不过粗略看了下这个插件的实现，它用到了另一个封装好的微信请求库，要让这个插件能够使用当前的方法登陆应该是要找那个微信请求库的作者做升级，这样这个插件的作者才有可能更新调用来使用。

作者大神你好，请问新注册手机号，有办法避免“为了你的帐号安全，此微信号不能登录网页微信”限制，正常登录网页版呢？

**Comment by BlueSky-07** [comment]
不太清楚新注册手机号的机制，可以试试当前这个可不可以用。
